services:
  test:
      container_name: "test"
      image: axjo21/microblog-tests:1.0.0-tests
      volumes:
        - ./app:/home/microblog/app
        - ./tests:/home/microblog/tests
      restart: no

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    networks:
      microblog:
        ipv4_address: 192.168.1.100
    restart: "always"
    volumes:
      - db_data:/var/lib/mysql

  prod:
    container_name: "microblog-server"
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    ports:
      - 8000:5000
    depends_on:
      - mysql
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      microblog:
        ipv4_address: 192.168.1.101
    restart: "always"

networks:
  microblog:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  db_data:
