name: Continous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip3 install -r /requirements/test.txt
          sudo apt-get update
          sudo apt-get install -y make

      - name: Run Tests
        run: |
          make test
