name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  run-test-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # login to docker using secret variables
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull test container image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/microblog-tests:1.0.0-tests

      - name: Run the container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/app:/home/microblog/app \
            -v ${{ github.workspace }}/tests:/home/microblog/tests \
            ${{ secrets.DOCKER_USERNAME }}/microblog-tests:1.0.0-tests
