name: Continuous Delivery

# on:
#     workflow_run:
#         workflows: [Continuous Integration]
#         types:
#             - completed
#         branches: [ master ]

on:
  release:
    types:
      - published
            
jobs:
    # Build and push docker images to DockerHub
    build-and-push:
        runs-on: ubuntu-latest
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
          - name: release tag name
            run: echo ${{ github.event.release.tag_name }}
            # - name: Checkout code
            #   uses: actions/checkout@v3

            # - name: Log in to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_TOKEN }}

            # - name: Build Docker image
            #   run: |
            #     docker compose build
            #     docker tag microblog-prod:latest ${{ secrets.DOCKER_USERNAME }}/microblog-prod:${{ github.sha }}
            #     docker tag microblog-prod:latest ${{ secrets.DOCKER_USERNAME }}/microblog-prod:latest
            # - name: Push Docker image
            #   run: |
            #     docker push ${{ secrets.DOCKER_USERNAME }}/microblog-prod:${{ github.sha }}
            #     docker push ${{ secrets.DOCKER_USERNAME }}/microblog-prod:latest
