name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  run-test-container:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.get_tag.outputs.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get release tag
        id: get_tag
        if: ${{ github.event_name == 'release' }}
        run: echo "::set-output name=tag_name::${{ github.event.release.tag_name }}"

      # login to docker using secret variables
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull test container image
        run: docker pull axjo21/microblog-tests:1.0.0-tests

      - name: Run the container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/app:/home/microblog/app \
            -v ${{ github.workspace }}/tests:/home/microblog/tests \
            axjo21/microblog-tests:1.0.0-tests
      - name: Debug Success
        run: echo "Workflow 1 completed successfully."

