name: CD - Build and push docker images to DockerHub

on:
    workflow_run:
        workflows:
        - CI - Validation, Unit & Integration tests
        types:
        - completed
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                docker compose build
                docker tag microblog-prod:latest ${{ secrets.DOCKER_USERNAME }}/microblog-prod:${{ github.sha }}
            - name: Push Docker image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/microblog-prod:${{ github.sha }}
