name: Continuous Delivery

on:
    workflow_run:
        workflows: [Continuous Integration]
        types:
            - completed
        # branches: [ master ]
            
jobs:
    # Build and push docker images to DockerHub
    build-and-push:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Debug Event Context
              run: |
                echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
                echo "Tag name from outputs: ${{ github.event.workflow_run.outputs.tag_name }}"

            - name: Extract tag_name from triggering workflow
              run: echo ${{ github.event.workflow_run.outputs.tag_name }}

            # - name: Checkout code
            #   uses: actions/checkout@v3

            # - name: Log in to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_TOKEN }}

            # - name: Build Docker image
            #   run: |
            #     docker compose build
            #     docker tag microblog-prod:latest ${{ secrets.DOCKER_USERNAME }}/microblog-prod:${{ github.event.release.tag_name }}
            #     docker tag microblog-prod:latest ${{ secrets.DOCKER_USERNAME }}/microblog-prod:latest
            # - name: Push Docker image
            #   run: |
            #     docker push ${{ secrets.DOCKER_USERNAME }}/microblog-prod:${{ github.event.release.tag_name }}
            #     docker push ${{ secrets.DOCKER_USERNAME }}/microblog-prod:latest
